---
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_VERSION="~> 3.5"
  - PUPPET_VERSION="~> 3.6"
  - PUPPET_VERSION="~> 3.7"
  - PUPPET_VERSION="~> 3"
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.0.0
